version: '3.8'

services:
  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  blockchain-go:
    build:
      context: ./blockchain
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./blockchain/data:/app/data
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - MONGO_URL=mongodb://mongo:27017/suape
      - GO_BLOCKCHAIN_URL=http://blockchain-go:8080/mine
      - ETH_ENABLED=false
      - PORT=3000
    depends_on:
      - mongo
      - blockchain-go
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - VITE_API_URL=http://localhost:3000
    ports:
      - "5173:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongo_data: 